// this file is autogenerated with the update-esm-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { deserialize, MARKER_BROWSER_ERROR, browserScript } = cjsEntrypoint;

export { deserialize, MARKER_BROWSER_ERROR, browserScript };
