// this file is autogenerated with the update-esm-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { setViewportPlugin, emulateMediaPlugin, setUserAgentPlugin } = cjsEntrypoint;

export { setViewportPlugin, emulateMediaPlugin, setUserAgentPlugin };
