// this file is autogenerated with the generate-mjs-dts-entrypoints script

export {
  setViewportPlugin,
  emulateMediaPlugin,
  selectOptionPlugin,
  setUserAgentPlugin,
  sendKeysPlugin,
  sendMousePlugin,
  a11ySnapshotPlugin,
  filePlugin,
  snapshotPlugin,
} from './dist/index.js'
