// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const {
  setViewportPlugin,
  emulateMediaPlugin,
  setUserAgentPlugin,
  sendKeysPlugin,
  sendMousePlugin,
  a11ySnapshotPlugin,
  filePlugin,
  snapshotPlugin,
} = cjsEntrypoint;

export {
  setViewportPlugin,
  emulateMediaPlugin,
  setUserAgentPlugin,
  sendKeysPlugin,
  sendMousePlugin,
  a11ySnapshotPlugin,
  filePlugin,
  snapshotPlugin,
};
