// this file is autogenerated with the generate-mjs-dts-entrypoints script
import * as cjsEntrypoint from './dist/index.js';

const { nodeResolve, fromRollup, rollupAdapter, rollupBundlePlugin } = cjsEntrypoint;

export { nodeResolve, fromRollup, rollupAdapter, rollupBundlePlugin };
