// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { fromRollup, rollupAdapter } = cjsEntrypoint;

export { fromRollup, rollupAdapter };
