// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { playwright, PlaywrightLauncher, devices, playwrightLauncher } = cjsEntrypoint;

export { playwright, PlaywrightLauncher, devices, playwrightLauncher };
