// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { injectPolyfillsLoader, hasFileOfType, fileTypes, getScriptFileType } = cjsEntrypoint;

export { injectPolyfillsLoader, hasFileOfType, fileTypes, getScriptFileType };
