// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const {
  createPolyfillsData,
  createPolyfillsLoader,
  injectPolyfillsLoader,
  hasFileOfType,
  fileTypes,
  getScriptFileType,
} = cjsEntrypoint;

export {
  createPolyfillsData,
  createPolyfillsLoader,
  injectPolyfillsLoader,
  hasFileOfType,
  fileTypes,
  getScriptFileType,
};
