// this file is autogenerated with the generate-mjs-dts-entrypoints script
export {
  createPolyfillsData,
  createPolyfillsLoader,
  injectPolyfillsLoader,
  hasFileOfType,
  fileTypes,
  getScriptFileType,
} from './dist/index.js'
