// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { createSauceLabsLauncher } = cjsEntrypoint;

export { createSauceLabsLauncher };
