// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { ChromeLauncher, puppeteerCore, chromeLauncher } = cjsEntrypoint;

export { ChromeLauncher, puppeteerCore, chromeLauncher };
