// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { webdriverLauncher, WebdriverLauncher } = cjsEntrypoint;

export { webdriverLauncher, WebdriverLauncher };
