name: Lint

on: pull_request

env:
  FORCE_COLOR: true

jobs:
  verify-linux:
    timeout-minutes: 30
    name: Verify linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '18'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint