// this file is autogenerated with the update-esm-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { visualRegressionPlugin } = cjsEntrypoint;

export { visualRegressionPlugin };
