// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { visualRegressionPlugin } = cjsEntrypoint;

export { visualRegressionPlugin };
